{
   "_meta": {
       "hostvars": {}
   },
   "all": {
       "children": [
           "balacing",
           "nginx",
           "load",
           "load1",
           "load2",
           "nginx1",
           "nginx2",
           "nginx3"
       ]
   },
   "balancing": {
       "hosts": [
           "192.168.9.100",
           "192.168.9.101",
           "192.168.9.102"
       ]
   },
   "nginx": {
       "hosts": [
           "192.168.9.103",
           "192.168.9.104",
           "192.168.9.105"
       ]
    },
   "nginx1": {
       "hosts": [
           "192.168.9.103"
       ]
   },
   "nginx2": {
       "hosts": [
           "192.168.9.104"
       ]
   },
    "nginx3": {
       "hosts": [
           "192.168.9.105"
       ]
   },
   "load": {
       "hosts": [
           "192.168.9.100"
       ]
   },
   "load1": {
        "hosts": [
            "192.168.9.101"
        ]
   },
   "load2": {
        "hosts": [
            "192.168.9.102"
        ]
   }
}
